title: Subeta Styling by Hong
#description: A repository for Subeta templates
markdown: GFM
#theme: minima
remote_theme: jekyll/minima
minima:
  skin: dark
plugins:
  - jekyll-feed
  - jekyll-remote-theme
header_pages:
  README.md
